### ISSUE TITLE
ASF tomcat image webserver

### ISSUE THREAD

**Issue by vassilismourikis** [web-servers/jws-operator#116]
**Describe the bug**
Persistent logs feature not working for ASF tomcat image

**To Reproduce**
Create a webserver using an ASF image (for example quay.io/jfclere/tomcat-demo) and setting:
  ```
spec:
  enableAccessLogs: true
  useSessionClustering: true
  persistentLogs: true
```

**Expected behavior**
Creates a PV with catalina.out and access.log of every pod

**Additional context**
Instead tomcat is not configured as expected because some files such as catalina.sh and logging.properties are missing. Probably needs extra configuration for the image or a more clever "test.sh" script.
Pod's logs:
[examplee-69bfcf6f87-d2jcc-examplee.log](https://github.com/web-servers/jws-operator/files/9973169/examplee-69bfcf6f87-d2jcc-examplee.log)
